receivers:
  jaeger:
    protocols:
      grpc:

exporters:
  otlphttp/2:
    endpoint: http://data-prepper:21890
    cert_file: "/etc/certfile.crt"
    key_file: "/etc/keyfile.key"
    insecure: true
  logging:

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logging, otlphttp/2]
